### ISSUE TITLE
您好，请问一下这个项目的效果是检测烟头，还是检测有人正在抽烟？

### ISSUE THREAD

**Issue by Taichipeace** [thomas-yanxin/Cigarette-Detection#1]
是否会混淆掉在地上的烟头 和 有人正在吸烟的情况？谢谢

**Comment by thomas-yanxin** [comment]
检测烟头
| |
左右
|
|
***@***.***
|
在2022年4月17日 ***@***.***> 写道：

是否会混淆掉在地上的烟头 和 有人正在吸烟的情况？谢谢
